name: 'Slack Success'
description: Notifies slack success.
inputs:
  slack-notify-token:
    description: Slack Notify application token
    required: true
  channel-id:
    description: Slack channel ID you want to send the message to
    required: true
  author:
    description: Author of the workflow
    required: true
    
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Slack Notify
      uses: slackapi/slack-github-action@v1.25.0
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-notify-token }}
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        channel-id: ${{ inputs.channel-id }}
        # For posting a rich message using Block Kit
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Created By:* `${{inputs.author}}`"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Team:* Discover"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Jira Ref:* <https://jira.example.com/browse/TICKET_ID|Jira Ticket>"
                }
              }
            ]
          }
